server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/account/**
          filters:
            - Retry=3
        - id: exchange-service
          uri: lb://EXCHANGE-SERVICE
          predicates:
            - Path=/api/v1/exchange/**
          filters:
            - Retry=3
